package se.voxelmanip.cookie.util;

/**
 * Class containing misc. constant values used across the program
 * @author ROllerozxa
 */
public final class AppConfig {
    private AppConfig() { // Utility classes should not have a public or default constructor
        throw new IllegalStateException("Utility class");
    }

    /**
     * The cost of autoclickers, in cookies.
     */
    public static final int autoClickerCost = 10;

    /**
     * The cost of click upgrades, in cookies.
     */
    public static final int clickUpgradeCost = 20;

    /**
     * Amount of cookies that get generated by an autoclicker per second.
     */
    public static final int autoClickerGen = 1;

    /**
     * Frequency of which the autoclicker generates cookies, measured in milliseconds.
     */
    public static final int autoclickerFreq = 1000;

    /**
     * The upper cap on how many cookies can be generated from time travel when the program is closed
     */
    public static final int timeTravelCookieCap = 1000000;

    /**
     * Name of the file used for saving and loading the game.
     */
    public static final String saveFile = "cookies.dat";

    /**
     * Magic header for save file.
     */
    public static final String saveHeader = "KAKA";

    /**
     * Frequency of autosave, measured in milliseconds.
     */
    public static final int autosaveFreq = 3*1000;
}
